# #====== ONLY EDIT THE CONFIGURATION IN THIS FILE. NEVER EDIT USER DATA FROM HERE! ======
# ======= THIS FILE STORES USER DATA ========

#How long it takes to take off 1 level of thirst
time-in-seconds-to-remove-1: 180

#Amount of levels of thirst a player has
number-of-thirst-levels: 20

#Text on the sidebar
scoreboard-text: Thirst
ops-get-thirsty: false
replenish-water: 12
replenish-milk: 12
replenish-melon: 4
replenish-mushroom-soup: 9
multiple-world-support: false
multi-world1: world
multi-world2: world_nether
multi-world3: world_the_end

#THIRST MESSAGE SETTINGS
#If false, there will be no warning, low, danger death message.
use-thirst-messages: true

#Message to display if player dies from dehydration
death-message: YOU HAVE DIED FROM DEHYDRATION!

level9-message: Keep an eye on your thirst!
level8-message: Keep an eye on your thirst!
level7-message: Keep an eye on your thirst!
level6-message: Consider finding a drink soon!
level5-message: You are starting to feel dehydrated!
level4-message: DANGER Find a drink fast
level3-message: DANGER Find a drink fast
level2-message: DANGER Find a drink fast
level1-message: DANGER FIND A DRINK NOW!